### ISSUE TITLE
problem on AWS EC2

### ISSUE THREAD

**Issue by shiyuleixia** [felixge/fgprof#9]
This package can't work on AWS EC2.  I use the gin web frame，when I send a request to my api，it just can‘t catch the calling-stack for this api

**Comment by felixge** [comment]
This is not a lot of information to understand your problem.

I'm guessing you did the following:

1. Launch your application.
2. Start a fgprof profile recording lasting 30s.
3. Make a http request to your application.
4. Wait for the profile to finish.
5. Look at the profile and notice that your request handler function doesn't seem to appear.

If this is the case, the problem is most likely caused by your request handler executing too quickly for the profiler to catch it. Put a `time.Sleep(time.Second)` into your handler and see if this "fixes" your problem.

fgprof currently samples at 99 Hz, which means it will have a hard time detecting events lasting less than ~10ms.
